.env
auth/api/docker/nginx/conf.d/default.conf
expose/api/docker/nginx/conf.d/default.conf
infra/kubernetes/auth_api_nginx.tf
infra/kubernetes/auth_api_php.tf
infra/kubernetes/auth_worker.tf
infra/kubernetes/db.tf
infra/kubernetes/expose_api_nginx.tf
infra/kubernetes/expose_api_php.tf
infra/kubernetes/expose_front.tf
infra/kubernetes/expose_worker.tf
infra/kubernetes/minio.tf
infra/kubernetes/notify_api_nginx.tf
infra/kubernetes/notify_api_php.tf
infra/kubernetes/notify_worker.tf
infra/kubernetes/rabbitmq.tf
infra/kubernetes/redis.tf
infra/kubernetes/uploader_api_nginx.tf
infra/kubernetes/uploader_api_php.tf
infra/kubernetes/uploader_client.tf
infra/kubernetes/uploader_worker.tf
infra/kubernetes/variables.tf
notify/api/docker/nginx/conf.d/default.conf
uploader/api/docker/nginx/conf.d/default.conf

- change _ to - to be host-DNS compliant)

Kubernetes manifests / fix hostnames in nginx

---

README.md
auth/api/Dockerfile
auth/api/composer.json
auth/api/composer.lock
auth/api/docker/caching/composer.json
auth/api/docker/caching/composer.lock
auth/api/symfony.lock
bin/optimize-composer-docker-cache
expose/api/Dockerfile
expose/api/composer.json
expose/api/src/Controller/ReadAssetAction.php
expose/api/src/Serializer/Normalizer/AbstractRouterNormalizer.php
expose/api/src/Serializer/Normalizer/AssetNormalizer.php
infra/docker/dev/Dockerfile
infra/docker/dev/symfony.ini
notify/api/Dockerfile
notify/api/composer.json
notify/api/composer.lock
notify/api/docker/caching/composer.json
notify/api/docker/caching/composer.lock
notify/api/symfony.lock
uploader/api/Dockerfile
uploader/api/composer.json
uploader/api/composer.lock
uploader/api/docker/caching/composer.json
uploader/api/docker/caching/composer.lock
uploader/api/symfony.lock

update composer deps (security fixes),
add optimize composer docker cache command

move to php7.4,

---

expose/api/src/Doctrine/PublicationExtension.php
expose/api/src/Migrations/Version20201210170006.php
lib/acl-bundle/Entity/AccessControlEntry.php
uploader/api/src/Migrations/Version20201210171415.php

change ace objectId to UUID type

PS-274 take ACL into account in publication list,

---

doc/configure-ssl.md
infra/ssl/create-root-ca.sh

create a p12 certificate for local dev with ssl
ask for passphrase only once
[SKIP CI]

create a p12 certificate for local dev with ssl

---

databox/api/config/packages/admin.yaml
databox/api/config/services.yaml
databox/api/migrations/Version20220406111848.php
databox/api/migrations/Version20220406112910.php
databox/api/migrations/Version20220406113544.php
databox/api/migrations/Version20220406114452.php
databox/api/migrations/Version20220406124752.php
databox/api/src/Command/ESMappingValidateCommand.php
databox/api/src/Elasticsearch/Listener/PopulatePassListener.php
databox/api/src/Elasticsearch/Mapping/ElasticsearchClient.php
databox/api/src/Elasticsearch/Mapping/IndexMappingDiff.php
databox/api/src/Elasticsearch/Mapping/IndexMappingUpdater.php
databox/api/src/Elasticsearch/Mapping/IndexSyncState.php
databox/api/src/Entity/Admin/ESIndexState.php
databox/api/src/Entity/Admin/PopulatePass.php
databox/api/src/Repository/Cache/AttributeDefinitionRepositoryMemoryCachedDecorator.php
databox/api/src/Util/ArrayUtil.php
databox/api/src/Util/Time.php
databox/api/tests/ElasticSearch/Mapping/IndexMappingDiffTest.php

PS-419 add databox es mapping state

---

databox/api/migrations/Version20220927124802.php
databox/api/src/Border/Consumer/Handler/FileEntranceHandler.php
databox/api/src/Consumer/Handler/File/NewAssetFromBorderHandler.php
databox/api/src/Consumer/Handler/File/ReadMetadataHandler.php
databox/api/src/Entity/Core/File.php
databox/api/src/File/FileMetadataAccessorWrapper.php
databox/api/src/Metadata/MetadataNormalizer.php

extract metadata to uploaded file, store in File.metadata

PS-478-1_metadata-extraction

---

databox/api/migrations/Version20230130130021.php
databox/api/migrations/Version20230130130329.php
databox/api/src/Controller/UpdateUserPreferenceAction.php
databox/api/src/Entity/Core/UserPreference.php
databox/api/src/User/UserPreferencesManager.php
databox/client/src/api/user.ts
databox/client/src/components/Layout/ChangeTheme.tsx
databox/client/src/components/Media/Asset/Attribute/AttributeRowUI.tsx
databox/client/src/components/Media/Asset/Attribute/Attributes.tsx
databox/client/src/components/Media/Asset/PreviewPopover.tsx
databox/client/src/components/Media/Search/Pager.tsx
databox/client/src/components/Media/Search/SelectionActions.tsx
databox/client/src/components/Root.tsx
databox/client/src/components/Security/UserContext.ts
databox/client/src/components/User/Preferences/UserPreferencesContext.ts
databox/client/src/components/User/Preferences/UserPreferencesProvider.tsx

add user preferences

---

uploader/api/src/Controller/Admin/AssetCrudController.php
uploader/api/src/Controller/Admin/CommitCrudController.php
uploader/api/src/Controller/Admin/MultipartUploadCrudController.php
uploader/api/src/Controller/Admin/TargetCrudController.php

PS-549 : admin uploader - some fix - target definition help message uploader session order

---

databox/client/Dockerfile

PS-605_build-out-of-memory

---

databox/indexer/src/handlers/phraseanet/indexer.ts
databox/indexer/src/handlers/phraseanet/types.d.ts

fix: search phrnet only for collections of selected (unique) databox.

PS-630_fetch-stories-from-unknown-collection

---

databox/api/src/Api/InputTransformer/AttributeDefinitionInputTransformer.php
databox/api/src/Api/Model/Input/AttributeDefinitionInput.php
databox/api/src/Api/Model/Output/AttributeDefinitionOutput.php
databox/api/src/Api/OutputTransformer/AttributeDefinitionOutputTransformer.php
databox/api/src/Api/Processor/WithOwnerIdProcessorTrait.php
databox/indexer/README.md
databox/indexer/config/config.json
databox/indexer/doc/conf_phraseanet.md
databox/indexer/package.json
databox/indexer/src/databox/client.ts
databox/indexer/src/databox/strategy/collectionBasedOnPathStrategy.ts
databox/indexer/src/databox/types.d.ts
databox/indexer/src/handlers/phraseanet/CPhraseanetMetadata.ts
databox/indexer/src/handlers/phraseanet/CPhraseanetRecord.ts
databox/indexer/src/handlers/phraseanet/indexer.ts
databox/indexer/src/handlers/phraseanet/phraseanetClient.ts
databox/indexer/src/handlers/phraseanet/shared.ts
databox/indexer/src/handlers/phraseanet/types.d.ts
databox/indexer/src/indexers.ts
doc/databox-indexer.md
doc/dev.md
pnpm-lock.yaml

phraseanet indexer
- handle stories, field mapping, locales
- compose field value(s) (twig) 
- dispatch into collection tree (twig)

PS-638_indexer-attributes-locale

---

configurator/src/Configurator/Configurator.php
configurator/src/Configurator/Vendor/Keycloak/KeycloakConfigurator.php
configurator/src/Configurator/Vendor/Keycloak/KeycloakManager.php
dashboard/client/config-compiler.js
dashboard/client/src/ClientApp.tsx
dashboard/client/src/Dashboard.tsx
dashboard/client/src/DashboardBar.tsx
dashboard/client/src/Root.tsx
dashboard/client/src/index.tsx

dashboard: display admin links depending on roles

PS-597_dashboard-display-services-by-role

---

expose/api/src/Entity/Publication.php
expose/api/src/Entity/PublicationProfile.php

Backport to expose V2 , search for publication

PS-656 backport to v2 search publication

---

databox/indexer/src/handlers/phraseanet/CPhraseanetRecord.ts
databox/indexer/src/handlers/phraseanet/shared.ts

fix: ignore undefined/null metadata;subdefs on records

PS-671_error-importing-stories

---

lib/php/rendition-factory/src/Command/CreateCommand.php
lib/php/rendition-factory/src/FileFamilyGuesser.php
lib/php/rendition-factory/src/Transformer/Video/FFMpegTransformerModule.php

**ffmpeg transformer module**
add mimetype+family to video output
add video options
- video_kilobitrate
- audio_kilobitrate
- passes
- timeout
- threads

PS-670-rendition-video_enhance1

---

databox/api/Dockerfile
infra/docker/dev/Dockerfile

add php extension "exif" for imagine to get orientation

PS-692_rendition-autorotate

---

lib/php/rendition-factory/src/Command/CreateCommand.php
lib/php/rendition-factory/src/Transformer/Image/Imagine/BackgroundFillFilterLoader.php
lib/php/rendition-factory/src/Transformer/Image/Imagine/BackgroundFilterLoader.php
lib/php/rendition-factory/src/Transformer/Image/Imagine/ImagineFilterFactory.php

paste layers one by one, centered
- options `size` and `position` are removed
- option `transparency` is renamed `opacity` to conform to values 0=transparent ; 100=full opaque color

PS-720_alpha-tiff-center

---

databox/api/src/Command/DeleteWorkspaceCommand.php
databox/api/src/Doctrine/Delete/WorkspaceDelete.php

add `app:workspace:delete` cli with debug log (-vvv)

PS-757_cleanup-being-deleted

---

dashboard/client/tsconfig.json
databox/api/src/Integration/Core/ReadMetadata/ReadMetadataIntegration.php
databox/client/tsconfig.json
databox/indexer/tsconfig.check.json
expose/client/tsconfig.json
lib/js/storage/src/types.ts
uploader/client/tsconfig.json

run ReadMetadataIntegration only on AssetIngest

PS-778_duplicate-metadata-after-edit

---

databox/client/src/components/Media/CollectionMenuItem.tsx

add keys to (...) collection dropdown

PS-813_warning-js

---

bin/ops/configurator-configure.sh
bin/ops/configurator-migrate.sh
bin/ops/run-k8s-configurator-shell.sh

Moving Helm charts from alchemy-helm-charts-repo to https://github.com/alchemy-fr/phrasea-helm-charts

PS-848 Update run-k8s-configurator-shell.sh

---

databox/api/translations/messages.fr.yaml
databox/client/translations/de.json
databox/client/translations/fr.json
databox/client/translations/it.json

Phrasea translations
This PR adds and updates translation files for Italian, French, and German to support additional locales in the Phrasea project. Key changes include the complete initialization of Italian translations, updates and new keys in the French translations, and the addition of German translations with minor corrections.

PS-905 Phrasea localisation
